/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package explodingkittens2;


import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Jenn
 */
public class GameMenu extends javax.swing.JFrame {
        
    /**
     * Creates new form StartMenu
     * @param playerCount
     */
    
    
    private int playerCount;
    
    private Deck drawPileDeck = new Deck();
    private Deck discardPileDeck = new Deck();
    
    private Deck regCards = new Deck();
    private Deck expCards = new Deck();
    private Deck diffuseCards  = new Deck();
    private ArrayList<Player> players = new ArrayList();
    
    public GameMenu(ArrayList players)throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        this.players.addAll(players);
        playerCount=players.size();
        
        //init and deal regular cards
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        regCards.regularCardsInit();
        regCards.shuffle(); //shuffle for random hand
        regCards.print();
        regCards.dealCards(4,this.players);//deal regular cards
        
        //init and deal diffuse cards
        diffuseCards.diffCardsInit(playerCount);
        diffuseCards.dealCards(1,this.players);
        
        //init exploding Kitten cards
        expCards.expCardsInit(playerCount);
       
        //Players should have full starting decks
        
        //combine left over initialized decks into drawPileDeck
        drawPileDeck.combineDecks(regCards, expCards, diffuseCards);
        drawPileDeck.shuffle();
        System.out.println("\nPRINTING REG DECK:");
        System.out.println("\n\nDrawPile Size: "+drawPileDeck.getSize());
        
        initComponents();
        refreshGUI();
    }
    
    ///////////////////////////////////////
    
    public void refreshGUI(){
        setCurrentPlayerCard();
        setPlayerCards();
        //drawPileDeck.chanceOfKitten();
        
    }
    
    //Collections.rotate(list, 1)
    public void setCurrentPlayerCard(){
        currentPlayerLabel.setText(players.get(0).getName());
        currentPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/"+players.get(0).getIcon() +".png")));
        currentPlayerCardCount.setText("");
        players.get(0).loadCardButtons(scroller);
    }
    
    public void setPlayerCards(){
        if(players.size()>=2){
        player1Icon.setText(players.get(1).getName());
        player1Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/"+players.get(1).getIcon()+".png")));
        player1CardCount.setText("");
        }
        
        if(players.size()>=3){
        player2Icon.setText(players.get(2).getName());
        player2Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/"+players.get(2).getIcon() +".png")));
        player2CardCount.setText("");
        }
        
        if(players.size()==4){
        player3Icon.setText(players.get(3).getName());
        player3Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/"+players.get(3).getIcon() +".png")));
        player3CardCount.setText("");
        }
    }
    
    ///////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chanceOfKit = new javax.swing.JLabel();
        ticker = new javax.swing.JLabel();
        phase = new javax.swing.JLabel();
        startMenuButton = new javax.swing.JButton();
        currentPlayerCard = new javax.swing.JPanel();
        handScroller = new javax.swing.JScrollPane();
        scroller = new javax.swing.JPanel();
        currentPlayerCardCount = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        handBG = new javax.swing.JLabel();
        currentPlayerLabel = new javax.swing.JLabel();
        currentPlayerIcon = new javax.swing.JButton();
        playerCard1 = new javax.swing.JPanel();
        player2Icon = new javax.swing.JButton();
        player2CardCount = new javax.swing.JLabel();
        playerCard2 = new javax.swing.JPanel();
        player3Icon = new javax.swing.JButton();
        player3CardCount = new javax.swing.JLabel();
        playerCard3 = new javax.swing.JPanel();
        player1Icon = new javax.swing.JButton();
        player1CardCount = new javax.swing.JLabel();
        deckButton = new javax.swing.JButton();
        discardDeckButton = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        chanceOfKit.setFont(new java.awt.Font("AR CHRISTY", 1, 24)); // NOI18N
        chanceOfKit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chanceOfKit.setText("CofKit");
        chanceOfKit.setToolTipText("");
        chanceOfKit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(chanceOfKit);
        chanceOfKit.setBounds(1040, 630, 90, 30);

        ticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/tickerSmall.png"))); // NOI18N
        getContentPane().add(ticker);
        ticker.setBounds(1010, 410, 270, 310);

        phase.setBackground(new java.awt.Color(51, 0, 0));
        phase.setFont(new java.awt.Font("AR CHRISTY", 1, 36)); // NOI18N
        phase.setForeground(new java.awt.Color(255, 255, 255));
        phase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phase.setText("ACTION PHASE");
        phase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        phase.setOpaque(true);
        getContentPane().add(phase);
        phase.setBounds(0, 670, 1280, 50);

        startMenuButton.setFont(new java.awt.Font("AR CHRISTY", 1, 24)); // NOI18N
        startMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        startMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/buttonBG.png"))); // NOI18N
        startMenuButton.setText("BACK");
        startMenuButton.setBorderPainted(false);
        startMenuButton.setContentAreaFilled(false);
        startMenuButton.setFocusPainted(false);
        startMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startMenuButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/pressedBG.png"))); // NOI18N
        startMenuButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/pressedBG.png"))); // NOI18N
        startMenuButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/pressedBG.png"))); // NOI18N
        startMenuButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/pressedBG.png"))); // NOI18N
        startMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startMenuButton);
        startMenuButton.setBounds(320, 620, 185, 80);

        currentPlayerCard.setOpaque(false);
        currentPlayerCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        handScroller.setBackground(new java.awt.Color(0, 0, 0));
        handScroller.setBorder(null);
        handScroller.setForeground(new java.awt.Color(0, 0, 0));
        handScroller.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        handScroller.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        handScroller.setAutoscrolls(true);
        handScroller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handScroller.setFont(new java.awt.Font("AR CHRISTY", 0, 18)); // NOI18N

        scroller.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scroller.setLayout(new javax.swing.BoxLayout(scroller, javax.swing.BoxLayout.LINE_AXIS));
        handScroller.setViewportView(scroller);

        currentPlayerCard.add(handScroller, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 500, 240));

        currentPlayerCardCount.setBackground(new java.awt.Color(255, 204, 51));
        currentPlayerCardCount.setFont(new java.awt.Font("AR CHRISTY", 0, 18)); // NOI18N
        currentPlayerCardCount.setForeground(new java.awt.Color(153, 153, 153));
        currentPlayerCardCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentPlayerCardCount.setText("Cards: 31");
        currentPlayerCardCount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentPlayerCardCount.setIconTextGap(0);
        currentPlayerCardCount.setInheritsPopupMenu(false);
        currentPlayerCard.add(currentPlayerCardCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, -1));

        infoLabel.setBackground(new java.awt.Color(0, 0, 0));
        infoLabel.setFont(new java.awt.Font("AR CHRISTY", 0, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Selected Info");
        infoLabel.setToolTipText("");
        infoLabel.setOpaque(true);
        currentPlayerCard.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 20));

        handBG.setBackground(new java.awt.Color(0, 0, 0));
        handBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/cards/handBG.png"))); // NOI18N
        handBG.setOpaque(true);
        currentPlayerCard.add(handBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 520, 260));

        currentPlayerLabel.setBackground(new java.awt.Color(204, 204, 204));
        currentPlayerLabel.setFont(new java.awt.Font("AR CHRISTY", 1, 24)); // NOI18N
        currentPlayerLabel.setForeground(new java.awt.Color(51, 51, 51));
        currentPlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentPlayerLabel.setText("PLAYER NAME");
        currentPlayerLabel.setToolTipText("");
        currentPlayerLabel.setOpaque(true);
        currentPlayerCard.add(currentPlayerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 220, -1));

        currentPlayerIcon.setFont(new java.awt.Font("AR CHRISTY", 1, 24)); // NOI18N
        currentPlayerIcon.setForeground(new java.awt.Color(255, 255, 255));
        currentPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/chainSaw.png"))); // NOI18N
        currentPlayerIcon.setBorderPainted(false);
        currentPlayerIcon.setContentAreaFilled(false);
        currentPlayerIcon.setFocusPainted(false);
        currentPlayerIcon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        currentPlayerIcon.setIconTextGap(0);
        currentPlayerIcon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        currentPlayerIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPlayerIconActionPerformed(evt);
            }
        });
        currentPlayerCard.add(currentPlayerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 185, 150));

        getContentPane().add(currentPlayerCard);
        currentPlayerCard.setBounds(480, 0, 800, 320);

        playerCard1.setBackground(new java.awt.Color(51, 51, 51));
        playerCard1.setOpaque(false);

        player2Icon.setFont(new java.awt.Font("AR CHRISTY", 1, 20)); // NOI18N
        player2Icon.setForeground(new java.awt.Color(255, 255, 255));
        player2Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/avacado.png"))); // NOI18N
        player2Icon.setText("PLAYER NAME");
        player2Icon.setBorderPainted(false);
        player2Icon.setContentAreaFilled(false);
        player2Icon.setFocusPainted(false);
        player2Icon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        player2Icon.setIconTextGap(-40);
        player2Icon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        player2Icon.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/avacado.png"))); // NOI18N
        player2Icon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/selectIcon.png"))); // NOI18N
        player2Icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2IconActionPerformed(evt);
            }
        });
        playerCard1.add(player2Icon);

        player2CardCount.setBackground(new java.awt.Color(51, 0, 0));
        player2CardCount.setFont(new java.awt.Font("AR CHRISTY", 0, 18)); // NOI18N
        player2CardCount.setForeground(new java.awt.Color(51, 0, 0));
        player2CardCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2CardCount.setText("[Cards: 3]");
        player2CardCount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player2CardCount.setIconTextGap(0);
        player2CardCount.setInheritsPopupMenu(false);
        playerCard1.add(player2CardCount);

        getContentPane().add(playerCard1);
        playerCard1.setBounds(0, 240, 360, 190);

        playerCard2.setBackground(new java.awt.Color(51, 51, 51));
        playerCard2.setOpaque(false);

        player3Icon.setFont(new java.awt.Font("AR CHRISTY", 1, 20)); // NOI18N
        player3Icon.setForeground(new java.awt.Color(255, 255, 255));
        player3Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/nopeCat.png"))); // NOI18N
        player3Icon.setText("PLAYER NAME");
        player3Icon.setBorderPainted(false);
        player3Icon.setContentAreaFilled(false);
        player3Icon.setFocusPainted(false);
        player3Icon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        player3Icon.setIconTextGap(-40);
        player3Icon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        player3Icon.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/nopeCat.png"))); // NOI18N
        player3Icon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/selectIcon.png"))); // NOI18N
        player3Icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3IconActionPerformed(evt);
            }
        });
        playerCard2.add(player3Icon);

        player3CardCount.setBackground(new java.awt.Color(51, 0, 0));
        player3CardCount.setFont(new java.awt.Font("AR CHRISTY", 0, 18)); // NOI18N
        player3CardCount.setForeground(new java.awt.Color(51, 0, 0));
        player3CardCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3CardCount.setText("[Cards: 3]");
        player3CardCount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player3CardCount.setIconTextGap(0);
        player3CardCount.setInheritsPopupMenu(false);
        playerCard2.add(player3CardCount);

        getContentPane().add(playerCard2);
        playerCard2.setBounds(0, 430, 360, 190);

        playerCard3.setBackground(new java.awt.Color(51, 51, 51));
        playerCard3.setOpaque(false);

        player1Icon.setFont(new java.awt.Font("AR CHRISTY", 1, 20)); // NOI18N
        player1Icon.setForeground(new java.awt.Color(255, 255, 255));
        player1Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/pugcorn.png"))); // NOI18N
        player1Icon.setText("PLAYER NAME");
        player1Icon.setBorderPainted(false);
        player1Icon.setContentAreaFilled(false);
        player1Icon.setFocusPainted(false);
        player1Icon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        player1Icon.setIconTextGap(-40);
        player1Icon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        player1Icon.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/pugcorn.png"))); // NOI18N
        player1Icon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/playerIcons/selectIcon.png"))); // NOI18N
        player1Icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1IconActionPerformed(evt);
            }
        });
        playerCard3.add(player1Icon);

        player1CardCount.setBackground(new java.awt.Color(51, 0, 0));
        player1CardCount.setFont(new java.awt.Font("AR CHRISTY", 0, 18)); // NOI18N
        player1CardCount.setForeground(new java.awt.Color(51, 0, 0));
        player1CardCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1CardCount.setText("[Cards: 3]");
        player1CardCount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player1CardCount.setIconTextGap(0);
        player1CardCount.setInheritsPopupMenu(false);
        playerCard3.add(player1CardCount);

        getContentPane().add(playerCard3);
        playerCard3.setBounds(0, 50, 360, 190);

        deckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckInit.png"))); // NOI18N
        deckButton.setText("Deck");
        deckButton.setBorder(null);
        deckButton.setBorderPainted(false);
        deckButton.setContentAreaFilled(false);
        deckButton.setFocusPainted(false);
        deckButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deckButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckInit.png"))); // NOI18N
        deckButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckMess.png"))); // NOI18N
        deckButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckMess.png"))); // NOI18N
        deckButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckMess.png"))); // NOI18N
        deckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deckButton);
        deckButton.setBounds(440, 380, 290, 170);

        discardDeckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckBlankGray.png"))); // NOI18N
        discardDeckButton.setText("discardDeckButton");
        discardDeckButton.setBorderPainted(false);
        discardDeckButton.setContentAreaFilled(false);
        discardDeckButton.setFocusPainted(false);
        discardDeckButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        discardDeckButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckBlankDraw.png"))); // NOI18N
        discardDeckButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckBlankDraw.png"))); // NOI18N
        discardDeckButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckBlankDraw.png"))); // NOI18N
        discardDeckButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/deckBlankDraw.png"))); // NOI18N
        discardDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardDeckButtonActionPerformed(evt);
            }
        });
        getContentPane().add(discardDeckButton);
        discardDeckButton.setBounds(730, 470, 250, 170);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/explodingkittens2/images/gameBG.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ////////
    
    private void player1IconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1IconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1IconActionPerformed

    private void player3IconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3IconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3IconActionPerformed

    private void player2IconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2IconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2IconActionPerformed

    private void discardDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardDeckButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discardDeckButtonActionPerformed

    private void currentPlayerIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPlayerIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentPlayerIconActionPerformed

    ////////
    private void startMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMenuButtonActionPerformed
        // TODO add your handling code here:
        StartMenu g = new StartMenu();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_startMenuButtonActionPerformed

    private void deckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("clicked drawPile");
        Player tempPlayer = players.get(0);
        drawPileDeck.takeCard(tempPlayer);
        refreshGUI();
    }//GEN-LAST:event_deckButtonActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel chanceOfKit;
    private javax.swing.JPanel currentPlayerCard;
    private javax.swing.JLabel currentPlayerCardCount;
    private javax.swing.JButton currentPlayerIcon;
    private javax.swing.JLabel currentPlayerLabel;
    private javax.swing.JButton deckButton;
    private javax.swing.JButton discardDeckButton;
    private javax.swing.JLabel handBG;
    private javax.swing.JScrollPane handScroller;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel phase;
    private javax.swing.JLabel player1CardCount;
    private javax.swing.JButton player1Icon;
    private javax.swing.JLabel player2CardCount;
    private javax.swing.JButton player2Icon;
    private javax.swing.JLabel player3CardCount;
    private javax.swing.JButton player3Icon;
    private javax.swing.JPanel playerCard1;
    private javax.swing.JPanel playerCard2;
    private javax.swing.JPanel playerCard3;
    private javax.swing.JPanel scroller;
    private javax.swing.JButton startMenuButton;
    private javax.swing.JLabel ticker;
    // End of variables declaration//GEN-END:variables






}
